const piecesInfo = [
  { piece: "white-pawn", inUse: true, square: "A2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "B2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "C2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "D2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "E2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "F2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "G2", decimalCode: "9817" },
  { piece: "white-pawn", inUse: true, square: "H2", decimalCode: "9817" },
  { piece: "white-rook", inUse: true, square: "A1", decimalCode: "9814" },
  { piece: "white-knight", inUse: true, square: "B1", decimalCode: "9816" },
  { piece: "white-bishop", inUse: true, square: "C1", decimalCode: "9815" },
  { piece: "white-king", inUse: true, square: "E1", decimalCode: "9812" },
  { piece: "white-queen", inUse: true, square: "D1", decimalCode: "9813" },
  { piece: "white-bishop", inUse: true, square: "F1", decimalCode: "9815" },
  { piece: "white-knight", inUse: true, square: "G1", decimalCode: "9816" },
  { piece: "white-rook", inUse: true, square: "H1", decimalCode: "9814" },
  { piece: "black-pawn", inUse: true, square: "H7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "G7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "F7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "E7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "D7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "C7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "B7", decimalCode: "9823" },
  { piece: "black-pawn", inUse: true, square: "A7", decimalCode: "9823" },
  { piece: "black-rook", inUse: true, square: "H8", decimalCode: "9820" },
  { piece: "black-knight", inUse: true, square: "G8", decimalCode: "9822" },
  { piece: "black-bishop", inUse: true, square: "F8", decimalCode: "9821" },
  { piece: "black-king", inUse: true, square: "E8", decimalCode: "9818" },
  { piece: "black-queen", inUse: true, square: "D8", decimalCode: "9819" },
  { piece: "black-bishop", inUse: true, square: "C8", decimalCode: "9821" },
  { piece: "black-knight", inUse: true, square: "B8", decimalCode: "9822" },
  { piece: "black-rook", inUse: true, square: "A8", decimalCode: "9820" },
];

export default piecesInfo;
