const squaresInfo = {
  A1: { occupied: "white rook 1", specialMoves: ["castling A1"] },
  A2: { occupied: "white pawn 1", specialMoves: ["A4"] },
  A3: { occupied: false },
  A4: { occupied: false },
  A5: { occupied: false },
  A6: { occupied: false },
  A7: { occupied: "black pawn 8", specialMoves: ["A5"] },
  A8: { occupied: "black rook 2", specialMoves: ["castling A8"] },
  B1: { occupied: "white knight 1", specialMoves: false },
  B2: { occupied: "white pawn 2", specialMoves: ["B4"] },
  B3: { occupied: false },
  B4: { occupied: false },
  B5: { occupied: false },
  B6: { occupied: false },
  B7: { occupied: "black pawn 7", specialMoves: ["B5"] },
  B8: { occupied: "black knight 2", specialMoves: false },
  C1: { occupied: "white bishop 1", specialMoves: false },
  C2: { occupied: "white pawn 3", specialMoves: ["C4"] },
  C3: { occupied: false },
  C4: { occupied: false },
  C5: { occupied: false },
  C6: { occupied: false },
  C7: { occupied: "black pawn 6", specialMoves: ["C5"] },
  C8: { occupied: "black bishop 2", specialMoves: false },
  D1: { occupied: "white queen 1", specialMoves: false },
  D2: { occupied: "white pawn 4", specialMoves: ["D4"] },
  D3: { occupied: false },
  D4: { occupied: false },
  D5: { occupied: false },
  D6: { occupied: false },
  D7: { occupied: "black pawn 5", specialMoves: ["D5"] },
  D8: { occupied: "black queen 1", specialMoves: false },
  E1: { occupied: "white king", specialMoves: ["castling A1", "castling H1"] },
  E2: { occupied: "white pawn 5", specialMoves: ["E4"] },
  E3: { occupied: false },
  E4: { occupied: false },
  E5: { occupied: false },
  E6: { occupied: false },
  E7: { occupied: "black pawn 4", specialMoves: ["E5"] },
  E8: { occupied: "black king", specialMoves: ["castling A8", "castling H8"] },
  F1: { occupied: "white bishop 2", specialMoves: false },
  F2: { occupied: "white pawn 6", specialMoves: ["F4"] },
  F3: { occupied: false },
  F4: { occupied: false },
  F5: { occupied: false },
  F6: { occupied: false },
  F7: { occupied: "black pawn 3", specialMoves: ["F5"] },
  F8: { occupied: "black bishop 1", specialMoves: false },
  G1: { occupied: "white knight 2", specialMoves: false },
  G2: { occupied: "white pawn 7", specialMoves: ["G4"] },
  G3: { occupied: false },
  G4: { occupied: false },
  G5: { occupied: false },
  G6: { occupied: false },
  G7: { occupied: "black pawn 2", specialMoves: ["G5"] },
  G8: { occupied: "black knight 1", specialMoves: false },
  H1: { occupied: "white rook 1", specialMoves: ["castling H1"] },
  H2: { occupied: "white pawn 8", specialMoves: ["H4"] },
  H3: { occupied: false },
  H4: { occupied: false },
  H5: { occupied: false },
  H6: { occupied: false },
  H7: { occupied: "black pawn 1", specialMoves: ["H5"] },
  H8: { occupied: "black rook 1", specialMoves: ["castling H8"] },
};

export default squaresInfo;
