const piecesInfo = [
  { piece: "white-pawn", inUse: true, square: "A2" },
  { piece: "white-pawn", inUse: true, square: "B2" },
  { piece: "white-pawn", inUse: true, square: "C2" },
  { piece: "white-pawn", inUse: true, square: "D2" },
  { piece: "white-pawn", inUse: true, square: "E2" },
  { piece: "white-pawn", inUse: true, square: "F2" },
  { piece: "white-pawn", inUse: true, square: "G2" },
  { piece: "white-pawn", inUse: true, square: "H2" },
  { piece: "white-rook", inUse: true, square: "A1" },
  { piece: "white-knight", inUse: true, square: "B1" },
  { piece: "white-bishop", inUse: true, square: "C1" },
  { piece: "white-king", inUse: true, square: "E1" },
  { piece: "white-queen", inUse: true, square: "D1" },
  { piece: "white-bishop", inUse: true, square: "F1" },
  { piece: "white-knight", inUse: true, square: "G1" },
  { piece: "white-rook", inUse: true, square: "H1" },
  { piece: "black-pawn", inUse: true, square: "H7" },
  { piece: "black-pawn", inUse: true, square: "G7" },
  { piece: "black-pawn", inUse: true, square: "F7" },
  { piece: "black-pawn", inUse: true, square: "E7" },
  { piece: "black-pawn", inUse: true, square: "D7" },
  { piece: "black-pawn", inUse: true, square: "C7" },
  { piece: "black-pawn", inUse: true, square: "B7" },
  { piece: "black-pawn", inUse: true, square: "A7" },
  { piece: "black-rook", inUse: true, square: "H8" },
  { piece: "black-knight", inUse: true, square: "G8" },
  { piece: "black-bishop", inUse: true, square: "F8" },
  { piece: "black-king", inUse: true, square: "E8" },
  { piece: "black-queen", inUse: true, square: "D8" },
  { piece: "black-bishop", inUse: true, square: "C8" },
  { piece: "black-knight", inUse: true, square: "B8" },
  { piece: "black-rook", inUse: true, square: "A8" },
];

export default piecesInfo;